LR = 0.001  # Learning Rate
EPOCHS = 10
BATCH_SIZE = 32
EMBED_SIZE = 512
HIDDEN_SIZE = 512
DROPOUT = 0.4
OPTIMIZER = 'adam'  # Available: adam, adadelta, adagrad, rmsprop, sgd
VOCAB_THRESHOLD = 1
SEQUENCE_LENGTH = 50
OUTPUT_PATH = 'results/'
IMAGE_DATA_PATH = 'data/Images/'
TEXT_DATA_PATH = 'data/captions.txt'
